In [1]:
import pandas as pd
import numpy as np

In [5]:
electoralVotes = pd.read_csv('voting-weights/data/2016ElectoralVotesLocal.csv')
stateVotes = pd.read_csv('voting-weights/data/state-votes.csv')

In [16]:
stateVotes = pd.read_csv('voting-weights/data/state-votes.csv')

In [14]:
statePopulations = pd.read_csv('voting-weights/data/StatePopulations.csv')

In [17]:
stateVotes

                   State    Trump  Clinton
0                Alabama  1306925   718084
1                 Alaska   116454   163387
2                Arizona   972900   888374
3               Arkansas   677904   378729
4             California  2970470  5488776
5               Colorado  1136354  1208095
6            Connecticut   637919   823360
7               Delaware   185103   235581
8   District of Columbia   282830    12723
9                Florida  4605515  4485745
10               Georgia  2068623  1837300
11                Hawaii   128815   266827
12                 Idaho   407199   189677
13              Illinois  2118179  2977498
14               Indiana  1556220  1031953
15                  Iowa   798923   650790
16                Kansas   656009   414788
17              Kentucky  1202942   628834
18             Louisiana  1178004   779535
19                 Maine   334838   354873
20              Maryland   873646  1497951
21         Massachusetts  1083069  1964768
22              Michigan  2279210  2267373
23             Minnesota  1322871  1366653
24           Mississippi   678457   462001
25              Missouri  1585753  1054889
26               Montana   274120   174521
27              Nebraska   485819   273858
28                Nevada   511319   537753
29         New Hampshire   345598   348126
30            New Jersey  1516915  1979768
31            New Mexico   315875   380724
32              New York  2637678  4143541
33        North Carolina  2339603  2162074
34          North Dakota   216133    93526
35                  Ohio  2771984  2317001
36              Oklahoma   947934   419788
37                Oregon   742506   934631
38          Pennsylvania  2912941  2844705
39          Rhode Island   166590   227052
40        South Carolina  1143611   849469
41          South Dakota   227701   117442
42             Tennessee  1517402   867110
43                 Texas  4681590  3867816
44                  Utah   375006   222858
45               Vermont    95050   178117
46              Virginia  1731156  1916845
47            Washington   835385  1221435
48         West Virginia   486198   187457
49             Wisconsin  1409467  1382210
50               Wyoming   174248    55949